name: Build Docker image and deploy to Portainer

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: unit and integration tests
        run: mvn -B test --file pom.xml
        env:
          MLB_DATA_USER: ${{secrets.MLB_DATA_USER}}
          MLB_DATA_PW: ${{secrets.MLB_DATA_PW}}
          MLB_DATA_IP: ${{secrets.MLB_DATA_IP}}

      - name: build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: webguy1979/mlb-rest-server:latest

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Deploy to Portainer 3
        uses: rrennoir/portainer-stack@v2
        with:
          portainerUrl: ${{ secrets.PORTAINER_URL }}
          portainerApiKey: ${{ secrets.PORTAINER_ACCES_TOKEN }}
          portainerEndpointId: 2
          stackName: mlb-rest-server
          stackType: 2
          composeFile: ./docker-compose.yml


