name: Build and test MLB REST Server Spring Boot Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify
        env:
          MLB_DATA_USER: ${{secrets.MLB_DATA_USER}}
          MLB_DATA_PW: ${{secrets.MLB_DATA_PW}}
          MLB_DATA_IP: ${{secrets.MLB_DATA_IP}}

      - name: Test Report
        uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: SpringBoot Report
          path: target/site/serenity/
